### ISSUE TITLE
Service Config JSON Key - MQTT vs REST request

### ISSUE THREAD

**Issue by linux4life798** [OpenChirp/openchirp_rest#18]
Before we get too deep, the device specific service config received from the services REST interface and from the service update over MQTT have almost identical JSON blobs. It is simply a difference of "config" vs a "service_config" key.
Could we standardize on maybe just "config" to compress service side data structures? I think the service part is implicit.

These lines look relevant, the second one more so:
https://github.com/OpenChirp/openchirp_rest/blob/master/src/models/device.js#L25
https://github.com/OpenChirp/openchirp_rest/blob/master/src/middleware/resource_managers/service_manager.js#L98

Best,

Craig

**Comment by khush-bhatia** [comment]
Changed it to use "config".

**Comment by linux4life798** [comment]
Cool. Thanks!
