### ISSUE TITLE
Publishing to a transducer returns a completely empty response

### ISSUE THREAD

**Issue by v1shanker** [OpenChirp/openchirp_rest#30]
trying to POST to a transducer fails with no indication of why. I know it's not the authorization header because I am able to GET. The endpoint I am referring to is below:

https://openchirp.github.io/api_doc/#publish-to-a-transducer

**Comment by linux4life798** [comment]
This should be fixed with https://github.com/OpenChirp/openchirp_rest/commit/fa75c366c47b72fdd7e260dd69fbeeaa61629a16 
and improved with https://github.com/OpenChirp/openchirp_rest/commit/3883db5e765034c822b5f712a57615a7903f124e .

Please confirm.

Thanks,

Craig

**Comment by linux4life798** [comment]
Confirmed to be working a while ago.
