### ISSUE TITLE
create new location doesn't seem to update GPS coordinates

### ISSUE THREAD

**Issue by anthonyrowe** [OpenChirp/openchirp_rest#32]
Running the following example seems to produce a blank "coordinates" field in the output:

POST /api/location/582e2b2c065b2545ded3aabd HTTP/1.1
{
  "name":"CIC",
  "type":"BUILDING",
    "geo_loc": {
      "coordinates": [
        40.4509146,
        -79.9024777
      ]     
    }    
}

**Comment by linux4life798** [comment]
1. Looks like there was a typo in the variable name for `geo_loc` in the update function.
Will push a patch in a minute.
2. You need to use `PUT` to make an update.
