### ISSUE TITLE
getThings (devices) should include more device information

### ISSUE THREAD

**Issue by hiliang-cmu** [OpenChirp/openchirp_rest#43]
For OpenChirp/website#122

https://github.com/OpenChirp/openchirp_rest/blob/732630365f7d06dd4946b5a956898477aed0493e/src/middleware/resource_managers/service_manager.js#L102

**Comment by linux4life798** [comment]
Yeah, I'm not sure where the line should be drawn between too much info about a device and not enough info about a device. I guess adding in the device name would not really incur any extra cost on the rest server itself, but would incur an extra cost of data transfer.
Note, whatever format of data gets returned by this call must/should also be mirrored over the mqtt service events topic.

**Comment by hiliang-cmu** [comment]
Per discussion, routes for getThings should be split:

Add to services/:id/getThings
- Name
- Owner.name
- Owner.email

(New) services/:id/deviceinfo:
- Name
- Service.status
- Owner.name
- Owner.email
- Location.name

**Comment by hiliang-cmu** [comment]
Also removed hardcoded

'type' = 'device'

**Comment by hiliang-cmu** [comment]
Resolved by #53
