### ISSUE TITLE
expressjs etag caching causing CORS conflicts

### ISSUE THREAD

**Issue by hiliang-cmu** [OpenChirp/openchirp_rest#46]
### Expected Behavior:
When browser makes API request 'Origin' header, REST interface [responds](https://github.com/OpenChirp/openchirp_rest/blob/ab52c83146c97a2a39d4415637a25ad0f42bda60/src/app.js#L40) with 'Access-Control-Allow-Origin' of same value as that 'Origin', thereby allowing CORS requests from other front-ends such as http://localhost or https://testing.openchirp.io 

### Current Behavior
expressjs provides caching [ETags](https://en.wikipedia.org/wiki/HTTP_ETag), apparently by default. 

Each API response includes an ETag hash of the response value. (There is no explicit cache expiration time specified). A browser making a subsequent request to same endpoint may include header "If-None-Match" with its last cached ETag value. If this matches the hash of the return data, expressjs will respond with **only** a HTTP 304 - NOT MODIFIED status and no data. This response also  **does not** include CORS headers.

As result, the cached XHR the browser uses *includes the previously cached CORS headers*. This will cause the browser to CORS error on the front-end. 

### Steps to reproduce
1. Log in to https://openchirp.io
2. Change URL to https://testing.openchirp.io
3. Orz

### Possible Solution
Disable [ETags ](https://expressjs.com/en/api.html#app.set) in expressjs config. For purposes of bandwidth-saving, HW devices are unlikely to support ETags anyhow.

**Comment by hiliang-cmu** [comment]
`app.disable('etag');`

**Comment by khush-bhatia** [comment]
Wouldn't this disable catching for all read requests ? I wouldn't disable etag.

I had solved the CORS issue before and it was working with website in one domain talking to rest api in another domain. What changed ?
